# Generated by Django 4.2 on 2025-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclient',
            name='c_address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myclient',
            name='c_city',
            field=models.CharField(default='lagos', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myclient',
            name='c_country',
            field=models.CharField(default='usa', max_length=100),
            preserve_default=False,
        ),
    ]
