# Generated by Django 4.2 on 2025-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myclient_c_address_alter_myclient_c_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclient',
            name='c_delivery_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='myclient',
            name='c_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
