# Generated by Django 4.2 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('order_key', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending, awaiting payment', 'Pending, awaiting payment'), ('Delivery in Progress', 'Delivery in Progress'), ('Delivered', 'Delivered'), ('Stopped by custom', 'Stopped by custom')], default='Pending, awaiting payment', max_length=150)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
